const std = @import("std");

const Allocator = std.mem.Allocator;

/// Configuration for an LLM interaction session.
pub const SessionConfig = struct {
    /// The model to be used for the session.
    model: Model,
    /// A list of tools available for the model to use during the session.
    tools: []const Tool,
};

/// Represents an LLM model provided by the backend.
pub const Model = struct {
    /// The unique identifier of the model.
    id: []const u8,
    /// A human-readable display name for the model.
    display_name: []const u8,
};

/// Defines a tool (function) that the LLM can call.
pub const Tool = struct {
    /// Defines a parameter for a tool.
    pub const Param = struct {
        /// Supported data types for a parameter.
        pub const Type = union(enum) {
            string,
            integer,
            float,
            boolean,
            enumeration: []const []const u8,
            array: *const Type,
        };

        /// The name of the parameter.
        name: []const u8,
        /// A description of what the parameter represents.
        description: []const u8,
        /// The data type of the parameter.
        type: Type,
        /// Indicates if the parameter is required for the tool call.
        required: bool = false,
    };

    /// The name of the tool.
    name: []const u8,
    /// A description of what the tool does.
    description: []const u8,
    /// A list of parameters accepted by the tool.
    parameters: []const Param,
};

/// The result of a request to list available models.
/// Memory must be freed using the `deinit` method.
pub const ListModelsResult = struct {
    /// The list of available models.
    models: []const Model,

    ptr: *anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        deinit: *const fn (ptr: *anyopaque) void,
    };

    /// Frees the resources associated with the ListModelsResult.
    pub fn deinit(self: *ListModelsResult) void {
        self.vtable.deinit(self.ptr);
        self.* = undefined;
    }
};

/// Represents a segment of the model's output.
pub const ModelOutput = union(enum) {
    text: []const u8,
};

/// Represents a thought segment from the model's reasoning process.
pub const Thought = struct {
    text: []const u8,
};

/// An argument provided to a tool call.
pub const Argument = struct {
    pub const Value = union(enum) {
        string: []const u8,
        integer: i64,
        float: f64,
        boolean: bool,
    };

    name: []const u8,
    value: Value,
};

/// Represents a request by the model to call a specific tool.
pub const ToolCall = struct {
    /// The unique identifier of this specific tool call request.
    id: []const u8,
    /// The name of the tool to be called.
    name: []const u8,
    /// The arguments provided for the tool call.
    arguments: []Argument,
};

/// The result of executing a step (interaction) with the LLM.
/// Memory must be freed using the `deinit` method.
pub const StepResult = struct {
    /// The final output text generated by the model.
    model_output: []const ModelOutput,
    /// Any thoughts or reasoning generated by the model before producing the output.
    thoughts: []const Thought,
    /// A list of tool calls requested by the model.
    tool_calls: []const ToolCall,

    ptr: *anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        deinit: *const fn (ptr: *anyopaque) void,
    };

    /// Frees the resources associated with the StepResult.
    pub fn deinit(self: *StepResult) void {
        self.vtable.deinit(self.ptr);
        self.* = undefined;
    }
};

/// Represents information required to continue an interaction with an LLM.
pub const StepContinuation = struct {
    ptr: *anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        deinit: *const fn (ptr: *anyopaque) void,
    };

    /// Frees the resources associated with the StepContinuation.
    pub fn deinit(self: *StepContinuation) void {
        self.vtable.deinit(self.ptr);
        self.* = undefined;
    }
};

/// Represents the outcome of executing a single interaction step with the LLM.
pub const StepOutcome = struct {
    /// The result of the step execution containing generated outputs, thoughts, and tool calls.
    result: StepResult,
    /// The continuation required to maintain conversation state for subsequent steps.
    continuation: StepContinuation,
};

/// Represents a single input step to the LLM.
pub const Step = union(enum) {
    /// A user-provided text prompt.
    prompt: []const u8,
    /// The result of a previously requested tool call.
    tool_result: ToolResult,
};

/// Represents the result of a tool call execution.
pub const ToolResult = struct {
    /// The name of the tool that was executed.
    tool_name: []const u8,
    /// The unique identifier of the tool call from a previous request by the model.
    id: []const u8,
    /// The output or result of the tool execution as a string.
    result: []const u8,

    allocator: Allocator,

    /// Initializes a new Agent-managed ToolResult and returns a reference to it via `llm.types.ToolResult`.
    ///
    /// This method duplicates `tool_name`, `id`, and `result` using the provided `allocator` and memory
    /// must be released via `deinit()`.
    pub fn init(allocator: Allocator, tool_name: []const u8, id: []const u8, result: []const u8) !ToolResult {
        const dupe_tool_name = try allocator.dupe(u8, tool_name);
        errdefer allocator.free(dupe_tool_name);
        const dupe_id = try allocator.dupe(u8, id);
        errdefer allocator.free(dupe_id);
        const dupe_result = try allocator.dupe(u8, result);
        errdefer allocator.free(dupe_result);

        return .{
            .tool_name = dupe_tool_name,
            .id = dupe_id,
            .result = dupe_result,
            .allocator = allocator,
        };
    }

    /// Initializes a new Agent-managed ToolResult and returns a reference to it via `llm.types.ToolResult`.
    ///
    /// This method duplicates `tool_name`, and `id` using the provided allocator but takes ownership of `result`.
    /// Memory must be released via `deinit()` and `result` must have been allocated with the same allocator
    /// passed to this function.
    pub fn initTakingResultOwnership(allocator: Allocator, tool_name: []const u8, id: []const u8, result: []const u8) !ToolResult {
        const dupe_tool_name = try allocator.dupe(u8, tool_name);
        errdefer allocator.free(dupe_tool_name);
        const dupe_id = try allocator.dupe(u8, id);
        errdefer allocator.free(dupe_id);

        return .{
            .tool_name = dupe_tool_name,
            .id = dupe_id,
            .result = result,
            .allocator = allocator,
        };
    }

    /// Deinitializes the ToolResult and frees all associated memory.
    ///
    /// This method must be called exactly once for each ToolResult when it is no longer needed.
    pub fn deinit(self: *ToolResult) void {
        self.allocator.free(self.tool_name);
        self.allocator.free(self.id);
        self.allocator.free(self.result);
        self.* = undefined;
    }
};

/// The type of a step in a streaming interaction.
pub const StepType = enum {
    thought,
    model_output,
    tool_call,
};

/// The info for starting a tool call step in a stream.
pub const ToolCallStart = struct {
    /// The unique ID of the tool call.
    id: []const u8,
    /// The name of the tool.
    name: []const u8,
};

/// The specific information for the start of a step, categorized by type.
pub const StepStartPayload = union(enum) {
    thought,
    model_output,
    tool_call: ToolCallStart,
};

/// The incremental update payload.
pub const Delta = union(enum) {
    /// Text content delta from the model output.
    model_output: ModelOutput,
    /// Thought content delta from the model's reasoning.
    thought: Thought,
    /// Arguments delta for tool call parameters, represented as well-typed parsed arguments.
    tool_call: []const Argument,
};

/// Payload for a step event in a streaming response.
pub const StepEvent = struct {
    /// The sequential index of the step receiving this event.
    index: u32,
    /// The incremental event representing a change to a step.
    event: Event,

    pub const Event = union(enum) {
        start: StepStartPayload,
        delta: Delta,
        end,
    };
};

/// The data chunk representing incremental updates in a streaming response.
pub const StreamingChunk = struct {
    /// The generic event that occurred.
    event: Event,

    /// The generic stream event.
    pub const Event = union(enum) {
        /// Fired when a new streaming interaction session is successfully initialized.
        interaction_created,
        /// Fired when a new step in the interaction begins or is updated.
        step_event: StepEvent,
        /// Fired when the entire streaming interaction has completed.
        interaction_completed,
    };
};

/// Callback function signature for processing streaming response chunks.
pub const StreamingCallback = *const fn (context: ?*anyopaque, chunk: StreamingChunk) void;
