const std = @import("std");

/// Configuration for an LLM interaction session.
pub const SessionConfig = struct {
    /// The model to be used for the session.
    model: Model,
    /// A list of tools available for the model to use during the session.
    tools: []const Tool,
};

/// Represents an LLM model provided by the backend.
pub const Model = struct {
    /// The unique identifier of the model.
    id: []const u8,
    /// A human-readable display name for the model.
    display_name: []const u8,
};

/// Defines a tool (function) that the LLM can call.
pub const Tool = struct {
    /// Defines a parameter for a tool.
    pub const Param = struct {
        /// Supported data types for a parameter.
        pub const Type = enum {
            string,
        };

        /// The name of the parameter.
        name: []const u8,
        /// A description of what the parameter represents.
        description: []const u8,
        /// The data type of the parameter.
        type: Type,
        /// Indicates if the parameter is required for the tool call.
        required: bool = false,
    };

    /// The name of the tool.
    name: []const u8,
    /// A description of what the tool does.
    description: []const u8,
    /// A list of parameters accepted by the tool.
    parameters: []const Param,
};

/// The result of a request to list available models.
/// Memory must be freed using the `deinit` method.
pub const ListModelsResult = struct {
    /// The list of available models.
    models: []const Model,

    ptr: *anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        deinit: *const fn (ptr: *anyopaque) void,
    };

    /// Frees the resources associated with the ListModelsResult.
    pub fn deinit(self: *ListModelsResult) void {
        self.vtable.deinit(self.ptr);
        self.* = undefined;
    }
};

/// The result of executing a step (interaction) with the LLM.
/// Memory must be freed using the `deinit` method.
pub const StepResult = struct {
    /// The final output text generated by the model.
    model_output: []const ModelOutput,
    /// Any thoughts or reasoning generated by the model before producing the output.
    thoughts: []const Thought,
    /// A list of tool calls requested by the model.
    tool_calls: []const ToolCall,

    ptr: *anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        deinit: *const fn (ptr: *anyopaque) void,
    };

    /// Frees the resources associated with the StepResult.
    pub fn deinit(self: *StepResult) void {
        self.vtable.deinit(self.ptr);
        self.* = undefined;
    }

    /// Represents a segment of the model's output.
    pub const ModelOutput = union(enum) {
        text: []const u8,
    };

    /// Represents a thought segment from the model's reasoning process.
    pub const Thought = struct {
        text: []const u8,
    };

    /// Represents a request by the model to call a specific tool.
    pub const ToolCall = struct {
        /// An argument provided to the tool call.
        pub const Argument = struct {
            name: []const u8,
            value: []const u8,
        };

        /// The unique identifier of this specific tool call request.
        id: []const u8,
        /// The name of the tool to be called.
        name: []const u8,
        /// The arguments provided for the tool call.
        arguments: []Argument,
    };
};

/// Represents a single input step to the LLM.
pub const Step = union(enum) {
    /// A user-provided text prompt.
    prompt: []const u8,
    /// The result of a previously requested tool call.
    tool_result: ToolResult,
};

/// Represents the result of a tool call execution.
pub const ToolResult = struct {
    /// The name of the tool that was executed.
    tool_name: []const u8,
    /// The unique identifier of the tool call from a previous request by the model.
    id: []const u8,
    /// The output or result of the tool execution as a string.
    result: []const u8,
};
